name: Scrape session version

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 7-20 * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-version:
    name: Check SessionNet Version
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16.3
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.3

    - uses: actions/checkout@v2.3.4

    - uses: actions/cache@v2.1.4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: build binary
      run: go build -o check-session main.go

    - name: Execute notifier
      run: ./check-session
